name: "Download extract .tgz precompiled libraries"
description: "Download and extract .tgz precompiled libraries from antares-deps and antares-simulator repository"
inputs:
  antares-deps-version:
    description: 'antares-deps version'
    required: true
  os:
    description: 'operational system used for github action'
    required: true
  buildtype:
    description: 'build type'
    required: false
    default: 'Release'
  ortools-url:
    description: 'URL for OR-Tools'
    required: true
  ortools-dir:
    description: 'Destination directory for OR-Tools'
    required: true

runs:
  using: "composite"
  steps: 
  - name: Download & extract antares-deps
    shell: bash
    run: |
           wget https://github.com/AntaresSimulatorTeam/antares-deps/releases/download/v${{inputs.antares-deps-version}}/rte-antares-deps-${{inputs.os}}-${{inputs.buildtype}}.tar.gz
           tar -xvf rte-antares-deps-${{inputs.os}}-${{inputs.buildtype}}.tar.gz
           rm -rf rte-antares-deps-${{inputs.os}}-${{inputs.buildtype}}.tar.gz

  - name: Download & extract OR-Tools
    shell: bash
    run: |
           cd ${{inputs.ortools-dir}}
           wget ${{inputs.ortools-url}} -O ortools.zip
           unzip ortools.zip
           rm ortools.zip
