#pragma once

#define OUI_ANTARES 1
#define NON_ANTARES 0
#define LINFINI_ANTARES 1.e+80
#define LINFINI_ENTIER 20000000

#define OPTIMISATION_LINEAIRE 1
#define OPTIMISATION_QUADRATIQUE 2

#define ZERO_RESERVE_J_MOINS1 1.e-2
