docs_dir: docs
site_name: Antares Simulator Documentation
repo_url: https://github.com/AntaresSimulatorTeam/Antares_Simulator
edit_uri: edit/doc/docs/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/Icone.png
  prev_next_buttons_location: none
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.top
    - navigation.expand
    - content.tabs.link
  #  - navigation.sections
  #   - header.autohide
  #   - toc.separate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: antares
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - 'Home': 'index.md'
  - 'Reference guide':
    - 'Introduction': 'reference-guide/01-introduction.md'
    - 'Data organization': 'reference-guide/02-data_organization.md'
    - 'Commands': 'reference-guide/03-commands.md'
    - 'Active windows': 'reference-guide/04-active_windows.md'
    - 'Output files': 'reference-guide/05-output_files.md'
    - 'Time-Series analysis and generation': 'reference-guide/06-time_series_analysis_and_generation.md'
    - 'Kirchhoff''s constraint generator': 'reference-guide/07-kirchhoffs_constraint_generator.md'
    - 'Miscellaneous': 'reference-guide/08-miscellaneous.md'
    - 'System requirements': 'reference-guide/09-system_requirements.md'
    - 'Command line': 'reference-guide/10-command_line.md'
    - 'Adequacy patch (v8.3.0+)': 'reference-guide/14-adequacy-patch.md'
    - 'File format changes': 'reference-guide/13-file-format.md'
    - 'Attribution notices': 'reference-guide/12-attribution_notices.md'
  - 'Optimisation problem' : 'reference-guide/11-modeling.md'
  - 'Build':
    - 'Introduction': 'build/0-Introduction.md'
    - 'Development requirements': 'build/1-Development-requirements.md'
    - 'Dependencies install': 'build/2-Dependencies-install.md'
    - 'Build': 'build/3-Build.md'
    - 'Tests (user)': 'build/4-Tests-user.md'
    - 'Tests (developer)' : 'build/4-Tests-dev.md'
    - 'Installer creation': 'build/5-Installer-creation.md'
    - 'Continuous Integration' : 'build/continuous-integration.md'
    - 'OR-tools integration' : 'build/ortools-integration.md'
  - 'Changelog': 'CHANGELOG.md'
  - 'External links':
    - 'Antares ecosystem' : 'https://antares-doc.readthedocs.io'
    - 'Antares website': 'https://antares-simulator.org'
    - 'RTE website': 'http://www.rte-france.com/'


plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://code.jquery.com/jquery-3.6.0.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

markdown_extensions:
  - footnotes
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

copyright: Copyright &copy; 2007 - 2024 RTE
