sonar.projectName=Antares_Simulator
sonar.projectKey=AntaresSimulatorTeam_Antares_Simulator
sonar.organization=antaressimulatorteam
sonar.projectVersion=10.0.1
# =====================================================
#   Properties that will be shared amongst all modules
# =====================================================
# SQ standard properties
sonar.sources=src
sonar.tests=src/tests
sonar.sourceEncoding=UTF-8

sonar.exclusions=src/ext/**,\
		 src/tests/**,\
		 src/ui/**,\
		 src/expressions/antlr-interface/**,\
		 src/libs/antares/additionalConstraintRhsExpression/**,\
		 src/libs/antares/scenarioGroupParser/scenarioBuilderExpression/**,\
		 src/libs/antares/reservesParsing/**

sonar.coverage.exclusions=src/ext/**,\
         src/tests/**,\
         src/distrib/**,\
         src/tools/**,\
         src/ui/**,\
         src/solver/constraints-builder/**,\
         src/libs/fswalker/**,\
         src/libs/antares/study/cleaner/**,\
         src/libs/antares/study/finder/**,\
         src/libs/antares/jit/**,\
         src/libs/antares/sys/**,\
         src/libs/antares/paths/**,\
         src/libs/antares/locator/**,\
         src/libs/antares/correlation/**,\
         src/libs/antares/study/ui-runtimeinfos.cpp,\
         src/libs/antares/study/include/antares/study/ui-runtimeinfos.h,\
         src/libs/antares/study/area/ui.cpp,\
         src/libs/antares/antlr-interface/**,\
         src/libs/antares/additionalConstraintRhsExpression/**,\
	     src/libs/antares/scenarioGroupParser/scenarioBuilderExpression/**

sonar.coverageReportPaths=coverage.xml
sonar.cfamily.threads=4
