/*
** This file is part of libyuni, a cross-platform C++ framework (http://libyuni.org).
**
** This Source Code Form is subject to the terms of the Mozilla Public License
** v.2.0. If a copy of the MPL was not distributed with this file, You can
** obtain one at http://mozilla.org/MPL/2.0/.
**
** github: https://github.com/libyuni/libyuni/
** gitlab: https://gitlab.com/libyuni/libyuni/ (mirror)
*/
#ifndef __GRAMMAR_PARSER_JSON_PARSER_SYMBOLS_H__
# define __GRAMMAR_PARSER_JSON_PARSER_SYMBOLS_H__


// Generated by grammar-converter



namespace Grammar
{
namespace JSON
{

	/*!
	** \brief All IDs for symbols
	*/
	enum Symbol
	{
		symUnknown = (uint) -1,
		//! EOF
		symNTEOF = 0,
		//! Error
		symNTError = 1,
		//! Whitespace
		symNTWhitespace = 2,
		//! ,
		symComma = 3,
		//! :
		symColon = 4,
		//! [
		symBracketLeft = 5,
		//! ]
		symBracketRight = 6,
		//! {
		symCurlyBracketLeft = 7,
		//! }
		symCurlyBracketRight = 8,
		//! false
		symTFalse = 9,
		//! null
		symTNull = 10,
		//! Number
		symTNumber = 11,
		//! String
		symTString = 12,
		//! true
		symTTrue = 13,
		//! Array
		symNTArray = 14,
		//! Elements
		symNTElements = 15,
		//! Json
		symNTJson = 16,
		//! Members
		symNTMembers = 17,
		//! Object
		symNTObject = 18,
		//! Pair
		symNTPair = 19,
		//! Value
		symNTValue = 20,
		//! The maximum number of symbols,
		symMax = 21,

	}; // enum







} // namespace JSON
} // namespace Grammar

#endif // __GRAMMAR_PARSER_JSON_PARSER_SYMBOLS_H__
