#pragma once

/* This file is generated by CMake */


/* stdint.h */
#cmakedefine YUNI_HAS_STDINT_H

/* stdio.h */
#cmakedefine YUNI_HAS_STDIO_H

/* string.h - memcmp, memcmpy... */
#cmakedefine YUNI_HAS_STRING_H

/* time.h */
#cmakedefine YUNI_HAS_TIME_H

/* assert.h */
#cmakedefine YUNI_HAS_ASSERT_H

/* errno.h */
#cmakedefine YUNI_HAS_ERRNO_H

/* cstddef */
#cmakedefine YUNI_HAS_CSTDDEF

/* dirent.h */
#cmakedefine YUNI_HAS_DIRENT_H

/* stdlib.h */
#cmakedefine YUNI_HAS_STDLIB_H

/* unistd.h */
#cmakedefine YUNI_HAS_UNISTD_H

/* fcntl.h */
#cmakedefine YUNI_HAS_FCNTL_H

/* cstdlib */
#cmakedefine YUNI_HAS_CSTDLIB

/* stdarg.h */
#cmakedefine YUNI_HAS_STDARG_H

/* va_copy */
#cmakedefine YUNI_HAS_VA_COPY

/* sys/sendfile.h */
#cmakedefine YUNI_HAS_SYS_SENDFILE_H




/* sys/types.h */
#cmakedefine YUNI_HAS_SYS_TYPES_H

/* winsock2.h */
#cmakedefine YUNI_HAS_WINSOCK_2

/* ShellApi.h */
#cmakedefine YUNI_HAS_SHELLAPI_H

/* climits */
#cmakedefine YUNI_HAS_CLIMITS

/* vector */
#cmakedefine YUNI_HAS_VECTOR

/* list */
#cmakedefine YUNI_HAS_LIST

/* map */
#cmakedefine YUNI_HAS_MAP

/* algorithm */
#cmakedefine YUNI_HAS_ALGORITHM

/* cassert */
#cmakedefine YUNI_HAS_CASSERT






/* C++0x support by gcc (-std=c++0x) */
#cmakedefine YUNI_HAS_GCC_CPP0X_SUPPORT

/* GCC __builtin_expect */
#cmakedefine YUNI_HAS_GCC_BUILTIN_EXPECT

/* GCC __builtin_popcount */
#cmakedefine YUNI_HAS_GCC_BUILTIN_POPCOUNT

/* long types - different from int */
#cmakedefine YUNI_HAS_LONG

/* int64_t, from stdint.h */
#cmakedefine YUNI_HAS_INT64_T

/* int128_t, from stdint.h */
#cmakedefine YUNI_HAS_INT128_T

/* uint */
#cmakedefine YUNI_HAS_UINT

/* ssize_t */
#cmakedefine YUNI_HAS_SSIZE_T



/* pthread pthread_getthreadid_np */
#cmakedefine YUNI_HAS_PTHREAD_GETTHREADID_NP

/* pthread pthread_attr_setstacksize */
#cmakedefine YUNI_HAS_PTHREAD_ATTR_SETSTACKSIZE





/* C++0x support: nullptr (GCC: only >= 4.6 with -std=gnu++0x, VS: only >= 10) */
#cmakedefine YUNI_HAS_NULLPTR

/* gcc __sync_add_and_fetch */
#cmakedefine YUNI_HAS_SYNC_ADD_AND_FETCH

/* C++11 constexpr */
#cmakedefine YUNI_HAS_CONSTEXPR

/* C++11 std::hash */
#cmakedefine YUNI_HAS_STL_HASH

/* C++11 std::unordered_map */
#cmakedefine YUNI_HAS_STL_UNORDERED_MAP

/* C++11 std::unordered_set */
#cmakedefine YUNI_HAS_STL_UNORDERED_SET

/* C++ gcc always inline */
#cmakedefine YUNI_HAS_GCC_ALWAYS_INLINE

/* C++ msvc force inline */
#cmakedefine YUNI_HAS_MSVC_FORCE_INLINE

/* C++ gcc attribute 'pure' */
#cmakedefine YUNI_HAS_GCC_ATTR_PURE

/* C++ gcc attribute 'const' */
#cmakedefine YUNI_HAS_GCC_ATTR_CONST

/* C++11 keyword override */
#cmakedefine YUNI_HAS_CPP_KEYWORD_OVERRIDE

/* C++11 keyword final */
#cmakedefine YUNI_HAS_CPP_KEYWORD_FINAL

/* C++11 move operator */
#cmakedefine YUNI_HAS_CPP_MOVE

/* C++11 lambda */
#cmakedefine YUNI_HAS_CPP_LAMBDA

/* C++11 static_assert */
#cmakedefine YUNI_HAS_CPP_STATIC_ASSERT

/* lambda for Yuni::Bind / Yuni::Event */
#if defined(YUNI_HAS_CPP_MOVE) && defined(YUNI_HAS_CPP_LAMBDA)
# define YUNI_HAS_CPP_BIND_LAMBDA
# endif
