name: "Install minizip"
description: "Download and install system wide minizip library"

runs:
  using: "composite"
  steps:
    - name: Build minizip
      shell: bash
      run: |
        source /opt/rh/devtoolset-10/enable || true # Ignore error if devtoolset-10 is not available
        wget https://github.com/zlib-ng/minizip-ng/archive/refs/tags/4.0.5.zip
        unzip 4.0.5.zip
        cd minizip-ng-4.0.5
        cmake -S . -B build \
        -DCMAKE_BUILD_TYPE=Release \
        -D MZ_BUILD_TESTS=OFF \
        -D MZ_LZMA=OFF \
        -D MZ_ZSTD=OFF \
        -D MZ_BZIP2=OFF \
        -D MZ_PKCRYPT=OFF \
        -D MZ_WZAES=OFF \
        -D MZ_OPENSSL=OFF \
        -D MZ_ICONV=OFF \
        -DZLIB_TAG=develop #Temporary fix for zlib issue https://github.com/zlib-ng/minizip-ng/issues/764
        cmake --build build --config Release 
        cmake --install build --prefix ${{github.workspace}}/install
