name: "Run cucumber tests"
description: "Run cucumber tests"
inputs:
  tags:
    description: 'Tags'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Python requirements
      shell: bash
      run: python3 -m pip install -r src/tests/cucumber_python/requirements.txt

    - name: Run tests
      shell: bash
      run: |
        cd src/tests/cucumber_python
        behave --tags ${{ inputs.simtest-tag }}
