name: "Run cucumber tests"
description: "Run cucumber tests"
inputs:
  feature:
    description: 'Feature file or folder to run (default runs all features in "features" folder)'
    required: false
    default: 'features'
  tags:
    description: 'Tags to run (default skips tests marked @flaky)'
    required: false
    default: '~@flaky'
runs:
  using: "composite"
  steps:
    - name: Install Python requirements
      shell: bash
      run: python3 -m pip install -r src/tests/cucumber/requirements.txt

    - name: Run tests
      shell: bash
      run: |
        cd src/tests/cucumber
        behave --tags ${{ inputs.tags }} ${{ inputs.feature }}
