* Generated by MPModelProtoExporter
*   Name             : 
*   Format           : Free
*   Constraints      : 0
*   Variables        : 1
*     Binary         : 0
*     Integer        : 0
*     Continuous     : 1
NAME          
ROWS
 N  COST
COLUMNS
    CAND.p_max  COST           400
BOUNDS
 UP BOUND       CAND.p_max    1000
ENDATA
