* Generated by MPModelProtoExporter
*   Name             : 
*   Format           : Free
*   Constraints      : 3
*   Variables        : 5
*     Binary         : 0
*     Integer        : 0
*     Continuous     : 5
NAME          
ROWS
 N  COST
 E  N_Balance_t0_s0
 L  G1_Max_generation_t0_s0
 L  CAND_Max_generation_t0_s0
COLUMNS
    N_spillage                 COST                            1  N_Balance_t0_s0                -1
    N_unsupplied_energy        COST                          501  N_Balance_t0_s0                 1
    G1_generation              COST                           45  N_Balance_t0_s0                 1
    G1_generation              G1_Max_generation_t0_s0         1
    CAND_generation            COST                           10  N_Balance_t0_s0                 1
    CAND_generation            CAND_Max_generation_t0_s0       1
    CAND_p_max                 CAND_Max_generation_t0_s0      -1
RHS
    RHS                        N_Balance_t0_s0               400  G1_Max_generation_t0_s0       200
    RHS                        CAND_Max_generation_t0_s0       0
BOUNDS
 PL BOUND                      N_spillage
 PL BOUND                      N_unsupplied_energy
 PL BOUND                      G1_generation
 PL BOUND                      CAND_generation
 UP BOUND                      CAND_p_max                   1000
ENDATA
