* Generated by MPModelProtoExporter
*   Name             : 
*   Format           : Free
*   Constraints      : 3
*   Variables        : 5
*     Binary         : 0
*     Integer        : 0
*     Continuous     : 5
NAME          
ROWS
 N  COST
 E  N.Balance
 L  G1.Max_generation
 L  CAND.Max_generation
COLUMNS
    N.spillage           COST                      1  N.Balance                -1
    N.unsupplied_energy  COST                    501  N.Balance                 1
    G1.generation        COST                     45  N.Balance                 1
    G1.generation        G1.Max_generation         1
    CAND.generation      COST                     10  N.Balance                 1
    CAND.generation      CAND.Max_generation       1
    CAND.p_max           CAND.Max_generation      -1
RHS
    RHS                  N.Balance               400  G1.Max_generation       200
    RHS                  CAND.Max_generation       0
BOUNDS
 PL BOUND                N.spillage
 PL BOUND                N.unsupplied_energy
 PL BOUND                G1.generation
 PL BOUND                CAND.generation
 UP BOUND                CAND.p_max             1000
ENDATA
