* Generated by MPModelProtoExporter
*   Name             : 
*   Format           : Free
*   Constraints      : 1
*   Variables        : 3
*     Binary         : 0
*     Integer        : 0
*     Continuous     : 3
NAME          
ROWS
 N  COST
 E  DISCRETE.Max_investment
COLUMNS
    CAND.p_max               COST                        490
    DISCRETE.p_max           COST                        200  DISCRETE.Max_investment       1
    DISCRETE.nb_units        DISCRETE.Max_investment     -10
RHS
    RHS                      DISCRETE.Max_investment       0
BOUNDS
 UP BOUND                    CAND.p_max                 1000
 PL BOUND                    DISCRETE.p_max
 UP BOUND                    DISCRETE.nb_units            10
ENDATA
