* Generated by MPModelProtoExporter
*   Name             : 
*   Format           : Free
*   Constraints      : 1
*   Variables        : 3
*     Binary         : 0
*     Integer        : 0
*     Continuous     : 3
NAME          
ROWS
 N  COST
 E  DISCRETE_Max_investment_t0_s0
COLUMNS
    CAND_p_max                     COST                              490
    DISCRETE_p_max                 COST                              200  DISCRETE_Max_investment_t0_s0       1
    DISCRETE_nb_units              DISCRETE_Max_investment_t0_s0     -10
RHS
    RHS                            DISCRETE_Max_investment_t0_s0       0
BOUNDS
 UP BOUND                          CAND_p_max                       1000
 PL BOUND                          DISCRETE_p_max
 UP BOUND                          DISCRETE_nb_units                  10
ENDATA
