* Generated by MPModelProtoExporter
*   Name             : 
*   Format           : Free
*   Constraints      : 4
*   Variables        : 7
*     Binary         : 0
*     Integer        : 0
*     Continuous     : 7
NAME          
ROWS
 N  COST
 E  my_node.balance_0
 L  already_installed_generator.max_generation_0
 L  continuous_generator_candidate.max_generation_0
 L  discrete_generator_candidate.max_generation_0
COLUMNS
    my_node.spillage_s0_t0                           COST                                                  1  my_node.balance_0                                    -1
    my_node.unsupplied_energy_s0_t0                  COST                                                501  my_node.balance_0                                     1
    already_installed_generator.generation_s0_t0     COST                                                 45  my_node.balance_0                                     1
    already_installed_generator.generation_s0_t0     already_installed_generator.max_generation_0          1
    continuous_generator_candidate.p_max             continuous_generator_candidate.max_generation_0      -1
    continuous_generator_candidate.generation_s0_t0  COST                                                 10  my_node.balance_0                                     1
    continuous_generator_candidate.generation_s0_t0  continuous_generator_candidate.max_generation_0       1
    discrete_generator_candidate.p_max               discrete_generator_candidate.max_generation_0        -1
    discrete_generator_candidate.generation_s0_t0    COST                                                 10  my_node.balance_0                                     1
    discrete_generator_candidate.generation_s0_t0    discrete_generator_candidate.max_generation_0         1
RHS
    RHS                                              my_node.balance_0                                   400  already_installed_generator.max_generation_0        200
    RHS                                              continuous_generator_candidate.max_generation_0      -0  discrete_generator_candidate.max_generation_0        -0
BOUNDS
 UP BOUND                                            my_node.spillage_s0_t0                            1e+06
 UP BOUND                                            my_node.unsupplied_energy_s0_t0                   1e+06
 UP BOUND                                            already_installed_generator.generation_s0_t0        200
 UP BOUND                                            continuous_generator_candidate.p_max               1000
 PL BOUND                                            continuous_generator_candidate.generation_s0_t0
 PL BOUND                                            discrete_generator_candidate.p_max
 PL BOUND                                            discrete_generator_candidate.generation_s0_t0
ENDATA
