* Generated by MPModelProtoExporter
*   Name             : 
*   Format           : Free
*   Constraints      : 1
*   Variables        : 3
*     Binary         : 0
*     Integer        : 1
*     Continuous     : 2
NAME          
ROWS
 N  COST
 E  discrete_generator_candidate.p_max_nb_units_relation
COLUMNS
  INTSTART  'MARKER'                            'INTORG'
    discrete_generator_candidate.nb_units                 discrete_generator_candidate.p_max_nb_units_relation     -10
  INTEND    'MARKER'                            'INTEND'
    continuous_generator_candidate.p_max                  COST                                                     490
    discrete_generator_candidate.p_max                    COST                                                     200  discrete_generator_candidate.p_max_nb_units_relation       1
RHS
    RHS                                                   discrete_generator_candidate.p_max_nb_units_relation      -0
BOUNDS
 UP BOUND                                                 continuous_generator_candidate.p_max                    1000
 PL BOUND                                                 discrete_generator_candidate.p_max
 UI BOUND                                                 discrete_generator_candidate.nb_units                     10
ENDATA
