# CODE GENERATOR

# find -mindepth 2 -maxdepth 2 -type d
STUDIES = [
    ["valid-draft", "052 Benchmark CPU RAM HDD - 4_draft"],
    ["valid-adq", "052 Benchmark CPU RAM HDD - 4_adq"],
    ["valid-filter-outputs", "no-geo-trim--linkVars"],
    ["valid-filter-outputs", "no-geo-trim--selVars-1"],
    ["valid-filter-outputs", "no-geo-trim--selVars-4"],
    ["valid-filter-outputs", "with-geo-trim--no-vars-by-plant"],
    ["valid-filter-outputs", "no-geo-trim--only-row-bal"],
    ["valid-filter-outputs", "no-geo-trim--full-selVars"],
    ["valid-filter-outputs", "no-geo-trim--selVars-2"],
    ["valid-filter-outputs", "no-geo-trim-adq-selVars-2"],
    ["valid-filter-outputs", "with-geo-trim--selVars-2"],
    ["valid-filter-outputs", "no-geo-trim--no-vars-by-plant"],
    ["valid-filter-outputs", "no-geo-trim--areaVars"],
    ["valid-filter-outputs", "draft--no-selVar"],
    ["valid-filter-outputs", "no-geo-trim--adq-selVars-1"],
    ["valid-filter-outputs", "no-geo-trim--no-row-bal"],
    ["valid-filter-outputs", "no-geo-trim--noVar"],
    ["valid-filter-outputs", "draft--hydrobind-no-selVar"],
    ["valid-filter-outputs", "no-geo-trim--selVars-3"],
    ["valid-filter-outputs", "with-geo-trim--selVars-1"],
    ["valid-defaillance", "V601-Def-negative-positive-zoneAA"],
    ["valid-defaillance", "V601-Def-negative-positive-zoneCC"],
    ["valid-defaillance", "V601-Def-negative-positive-zoneB"],
    ["valid-defaillance", "V601-Def-negative-positive-zoneBB"],
    ["valid-defaillance", "defaillance_positive_majore"],
    ["valid-defaillance", "V601-Def-negative-positive-zoneA"],
    ["valid-defaillance", "V601-Def-negative-positive-zoneC"],
    ["valid-hydroPricing", "Fast"],
    ["valid-hydroPricing", "Accurate"],
    ["valid-bind", "BIND-04"],
    ["valid-bind", "BIND-07"],
    ["valid-bind", "BIND-08"],
    ["valid-bind", "BIND-09"],
    ["valid-bind", "BIND-08-gen"],
    ["valid-bind", "BIND-03"],
    ["valid-bind", "BIND-06"],
    ["valid-bind", "BIND-06-gen"],
    ["valid-bind", "BIND-00-gen"],
    ["valid-bind", "BIND-01"],
    ["valid-bind", "BIND-11-gen"],
    ["valid-bind", "BIND-09-gen"],
    ["valid-bind", "BIND-11"],
    ["valid-bind", "BIND-04-gen"],
    ["valid-bind", "BIND-10"],
    ["valid-bind", "BIND-01-gen"],
    ["valid-bind", "BIND-05"],
    ["valid-bind", "BIND-02"],
    ["valid-bind", "BIND-07-gen"],
    ["valid-bind", "BIND-00"],
    ["valid-bind", "BIND-03-gen"],
    ["valid-bind", "BIND-10-gen"],
    ["valid-bind", "BIND-05-gen"],
    ["valid-bind", "BIND-02-gen"],
    ["valid-marginCost", "marginal_cost_interco-kirchhoff-ok"],
    ["valid-marginCost", "marginal cost revised"],
    ["valid-marginCost", "marginal_cost_interco_freeflow_ok"],
    ["valid-complex", "E2050-5y-6w-fast-mps"],
    ["valid-complex", "E2050-5y-6w-accurate-mps"],
    ["valid-complex", "hydrau_FRCH"],
    ["valid-thermal", "generic - some  OFF - some MUST - TSRM"],
    ["valid-thermal", "generic - some  OFF - no OFFMUST - TSGEN"],
    ["valid-thermal", "generic - some  OFF - some MUST - TSGEN"],
    ["valid-thermal", "generic - all ON - some MUST - TSGEN"],
    ["valid-thermal", "generic - all ON - some MUST - TSRM"],
    ["valid-thermal", "generic - some  OFF - no OFFMUST - TSRM"],
    ["valid-hydro", "H700-17"],
    ["valid-hydro", "H700-08"],
    ["valid-hydro", "H700-50"],
    ["valid-hydro", "H700-23"],
    ["valid-hydro", "H701-57"],
    ["valid-hydro", "H700-38"],
    ["valid-hydro", "H700-14"],
    ["valid-hydro", "H700-09"],
    ["valid-hydro", "H700-36"],
    ["valid-hydro", "H700-48"],
    ["valid-hydro", "H700-47"],
    ["valid-hydro", "H700-26"],
    ["valid-hydro", "H701-53"],
    ["valid-hydro", "H700-20"],
    ["valid-hydro", "H700-01"],
    ["valid-hydro", "H701-55"],
    ["valid-hydro", "H700-15"],
    ["valid-hydro", "H700-31"],
    ["valid-hydro", "H700-12"],
    ["valid-hydro", "H701-58"],
    ["valid-hydro", "H700-21"],
    ["valid-hydro", "H700-49"],
    ["valid-hydro", "H700-04"],
    ["valid-hydro", "H700-25"],
    ["valid-hydro", "H700-44"],
    ["valid-hydro", "H700-35"],
    ["valid-hydro", "H700-45"],
    ["valid-hydro", "H701-54"],
    ["valid-hydro", "H700-11"],
    ["valid-hydro", "H700-27"],
    ["valid-hydro", "H700-46"],
    ["valid-hydro", "H700-32"],
    ["valid-hydro", "H700-10"],
    ["valid-hydro", "H700-24"],
    ["valid-hydro", "H701-59"],
    ["valid-hydro", "H700-33"],
    ["valid-hydro", "H700-51"],
    ["valid-hydro", "H700-19"],
    ["valid-hydro", "H700-02"],
    ["valid-hydro", "H700-41"],
    ["valid-hydro", "H701-52"],
    ["valid-hydro", "H700-07"],
    ["valid-hydro", "H700-16"],
    ["valid-hydro", "H700-06"],
    ["valid-hydro", "H700-43"],
    ["valid-hydro", "H700-39"],
    ["valid-hydro", "H700-29"],
    ["valid-hydro", "H700-37"],
    ["valid-hydro", "H700-42"],
    ["valid-hydro", "H700-03"],
    ["valid-hydro", "H700-05"],
    ["valid-hydro", "H700-22"],
    ["valid-hydro", "H700-34"],
    ["valid-hydro", "H700-40"],
    ["valid-hydro", "H700-30"],
    ["valid-hydro", "H700-18"],
    ["valid-hydro", "H700-13"],
    ["valid-hydro", "H700-28"],
    ["valid-hydro", "H700-00"],
    ["valid-hydro", "H701-56"],
    ["valid-ts-gen-export", "TS generation-and-export-1000"],
    ["valid-ts-gen-export", "TS generation-and-export-100"],
    ["valid-parallel", "test-parallel-00_eco-acc-168"],
    ["valid-parallel", "test-parallel-03-random_nbrs_eco-acc-168"],
    ["valid-parallel", "test-parallelisation-complexe-pl-2on12Y_eco-acc-168"],
    ["valid-parallel", "test-parallel-loadsave-2node_eco-acc-168"],
    ["valid-parallel", "test-paral-cplx-pl-7on12-scBuild_eco-fast-24"],
    ["valid-parallel", "Four areas - DC law_eco-acc-168"],
    ["valid-parallel", "test-parallel-00_eco-fast-24"],
    ["valid-parallel", "test-parallel-02-noMustRun_eco-fast-24"],
    ["valid-parallel", "test-parallel-districts_eco-acc-168"],
    ["valid-parallel", "test-parallelisation-complexe-pl-2on12Y_eco-fast-24"],
    ["valid-parallel", "test-parallel-01_eco-fast-24"],
    ["valid-parallel", "test-paral-cplx-pl-7on12-scBuild_eco-acc-168"],
    ["valid-parallel", "test-parallel-02_eco-acc-168"],
    ["valid-parallel", "test-parallel-loadsave-2node_eco-fast-24"],
    ["valid-parallel", "test-parallel-01_eco-acc-168"],
    ["valid-parallel", "Multistage study-3-PTDF_eco-fast-24"],
    ["valid-parallel", "Four areas - DC law_eco-fast-24"],
    ["valid-parallel", "test-parallel-loadsave-1node_eco-acc-168"],
    ["valid-parallel", "test-parallel-loadsave-1node_eco-fast-24"],
    ["valid-parallel", "Multistage study-3-PTDF_eco-acc-168"],
    ["valid-parallel", "test-parallel-02_eco-fast-24"],
    ["valid-parallel", "test-parallel-03-random_nbrs_eco-fast-24"],
    ["valid-parallel", "test-parallel-02-noMustRun_eco-acc-168"],
    ["valid-parallel", "test-parallel-districts_eco-fast-24"],
    ["valid-hydroBind", "hydrobind-spxday-freemod"],
    ["valid-hydroBind", "hydrobind-Adequacy"],
    ["valid-hydroBind", "hydrobind-scenario_builder-tsgen"],
    ["valid-hydroBind", "hydrobind-scenario_builder-readymade"],
    ["valid-hydroBind", "hydrobind-spxweek-freemod"],
    ["valid-hydroBind", "hydrobind-spxweek-minexc"],
    ["valid-hydroBind", "hydrobind-draft"],
    ["valid-hydroBind", "hydrobind-spxday-minexc"],
]

f=open("out.py", "w")

def fmt(x):
    return x.replace("-","_")\
            .replace(" ","")\
            .replace("__", "_")\
            .lower()

for it in STUDIES:
    f.write(f"@pytest.mark.non_regression\n")
    f.write(f"@pytest.mark.{fmt(it[0])}\n")
    f.write("@pytest.mark.skipif(sys.platform==\"linux\",\n")
    f.write("                    reason=\"Results different between linux and windows.\")\n")
    f.write(f"def test_{fmt(it[1])}(use_ortools, ortools_solver, solver_path):\n")
    f.write(f"    study_path = NONREG_STUDIES_PATH / \"{it[0]}\" / \"{it[1]}\"\n")
    f.write("    run_study(solver_path, study_path, use_ortools, ortools_solver)\n")
    f.write("    enable_study_output(study_path, False)\n")
    f.write("    check_output_values(study_path)\n\n")
