# CODE GENERATOR

STUDIES = [
    # SHORT STUDIES
    ["valid-bind", "BIND-08-gen", "short"],
    ["valid-bind", "BIND-09-gen", "short"],
    ["valid-bind", "BIND-10-gen", "short"],
    ["valid-defaillance", "V601-Def-negative-positive-zoneA", "short"],
    ["valid-defaillance", "V601-Def-negative-positive-zoneAA", "short"],
    ["valid-defaillance", "V601-Def-negative-positive-zoneB", "short"],
    ["valid-defaillance", "V601-Def-negative-positive-zoneBB", "short"],
    ["valid-defaillance", "V601-Def-negative-positive-zoneCC", "short"],
    ["valid-filter-outputs", "draft--hydrobind-no-selVar", "short"],
    ["valid-hydro", "H700-00", "short"],
    ["valid-hydro", "H700-02", "short"],
    ["valid-hydro", "H700-03", "short"],
    ["valid-hydro", "H700-05", "short"],
    ["valid-hydro", "H700-06", "short"],
    ["valid-hydro", "H700-07", "short"],
    ["valid-hydro", "H700-08", "short"],
    ["valid-hydro", "H700-09", "short"],
    ["valid-hydro", "H700-11", "short"],
    ["valid-hydro", "H700-15", "short"],
    ["valid-hydro", "H700-16", "short"],
    ["valid-hydro", "H700-17", "short"],
    ["valid-hydro", "H700-20", "short"],
    ["valid-hydro", "H700-21", "short"],
    ["valid-hydro", "H700-25", "short"],
    ["valid-hydro", "H700-41", "short"],
    ["valid-hydro", "H700-42", "short"],
    ["valid-hydro", "H700-43", "short"],
    ["valid-hydro", "H700-47", "short"],
    ["valid-hydro", "H700-48", "short"],
    ["valid-hydro", "H700-49", "short"],
    ["valid-hydro", "H700-50", "short"],
    ["valid-marginCost", "marginal_cost_interco-kirchhoff-ok", "short"],
    ["valid-marginCost", "marginal_cost_interco_freeflow_ok", "short"],
    ["valid-parallel", "test-parallel-districts_eco-acc-168", "short"],
    ["valid-parallel", "test-parallel-loadsave-1node_eco-acc-168", "short"],
    ["valid-parallel", "test-parallel-loadsave-1node_eco-fast-24", "short"],
    ["valid-parallel", "test-parallel-loadsave-2node_eco-acc-168", "short"],
    ["valid-parallel", "test-parallel-loadsave-2node_eco-fast-24", "short"],
    ["valid-bind", "BIND-07-gen", "short"],
    ["valid-bind", "BIND-11-gen", "short"],
    ["valid-defaillance", "V601-Def-negative-positive-zoneC", "short"],
    ["valid-hydro", "H700-01", "short"],
    ["valid-hydro", "H700-04", "short"],
    ["valid-hydro", "H700-10", "short"],
    ["valid-hydro", "H700-14", "short"],
    ["valid-hydro", "H700-18", "short"],
    ["valid-hydro", "H700-19", "short"],
    ["valid-hydro", "H700-22", "short"],
    ["valid-hydro", "H700-23", "short"],
    ["valid-hydro", "H700-26", "short"],
    ["valid-hydro", "H700-27", "short"],
    ["valid-hydro", "H700-28", "short"],
    ["valid-hydro", "H700-35", "short"],
    ["valid-hydro", "H700-36", "short"],
    ["valid-hydro", "H700-37", "short"],
    ["valid-hydro", "H700-38", "short"],
    ["valid-hydro", "H700-39", "short"],
    ["valid-hydro", "H700-40", "short"],
    ["valid-hydro", "H700-45", "short"],
    ["valid-hydroPricing", "Accurate/Few_weeks-five-areas/hydro-pricing-01", "short"],
    ["valid-hydroPricing", "Accurate/Few_weeks-five-areas/hydro-pricing-02", "short"],
    ["valid-hydroPricing", "Accurate/Few_weeks-five-areas/hydro-pricing-03", "short"],
    ["valid-hydroPricing", "Accurate/Few_weeks-five-areas/hydro-pricing-04", "short"],
    ["valid-hydroPricing", "Accurate/Few_weeks-five-areas/hydro-pricing-05", "short"],
    ["valid-hydroPricing", "Accurate/YHT-one_node_different styles/hydro-pricing-HE", "short"],
    ["valid-hydroPricing", "Accurate/YHT-one_node_different styles/hydro-pricing-M", "short"],
    ["valid-hydroPricing", "Fast/Few_weeks-five-areas/hydro-pricing-01", "short"],
    ["valid-hydroPricing", "Fast/Few_weeks-five-areas/hydro-pricing-02", "short"],
    ["valid-hydroPricing", "Fast/Few_weeks-five-areas/hydro-pricing-03", "short"],
    ["valid-hydroPricing", "Fast/Few_weeks-five-areas/hydro-pricing-04", "short"],
    ["valid-hydroPricing", "Fast/Few_weeks-five-areas/hydro-pricing-05", "short"],
    ["valid-hydroPricing", "Fast/YHT-one_node_different styles/hydro-pricing-HE", "short"],
    ["valid-hydroPricing", "Fast/YHT-one_node_different styles/hydro-pricing-M_hb", "short"],
    ["valid-marginCost", "marginal cost revised", "short"],
    ["valid-parallel", "Four areas - DC law_eco-fast-24", "short"],
    ["valid-parallel", "test-parallel-districts_eco-fast-24", "short"],
    ["valid-bind", "BIND-04-gen", "short"],
    ["valid-bind", "BIND-05-gen", "short"],
    ["valid-bind", "BIND-06-gen", "short"],
    ["valid-filter-outputs", "draft--no-selVar", "short"],
    ["valid-filter-outputs", "no-geo-trim--adq-selVars-1", "short"],
    ["valid-filter-outputs", "no-geo-trim--linkVars", "short"],
    ["valid-filter-outputs", "no-geo-trim--only-row-bal", "short"],
    ["valid-hydro", "H700-12", "short"],
    ["valid-hydro", "H700-13", "short"],
    ["valid-hydro", "H700-24", "short"],
    ["valid-hydro", "H700-29", "short"],
    ["valid-hydro", "H700-33", "short"],
    ["valid-hydro", "H700-46", "short"],
    ["valid-hydroBind", "hydrobind-scenario_builder-readymade", "short"],
    ["valid-hydroBind", "hydrobind-scenario_builder-tsgen", "short"],
    ["valid-hydroPricing", "Accurate/YHT-one_node_different styles/hydro-pricing-E", "short"],
    ["valid-hydroPricing", "Accurate/YHT-one_node_different styles/hydro-pricing-E_hb", "short"],
    ["valid-hydroPricing", "Accurate/YHT-one_node_different styles/hydro-pricing-M_hb", "short"],
    ["valid-hydroPricing", "Fast/YHT-one_node_different styles/hydro-pricing-E", "short"],
    ["valid-hydroPricing", "Fast/YHT-one_node_different styles/hydro-pricing-M", "short"],
    ["valid-parallel", "test-parallel-00_eco-acc-168", "short"],
    ["valid-parallel", "test-parallel-00_eco-fast-24", "short"],
    ["valid-thermal", "generic - all ON - some MUST - TSRM", "short"],
    ["valid-thermal", "generic - some  OFF - no OFFMUST - TSRM", "short"],
    ["valid-thermal", "generic - some  OFF - some MUST - TSRM", "short"],
    ["valid-ts-gen-export", "TS generation-and-export-10", "short"],
    ["valid-defaillance", "defaillance_positive_majore", "short"],
    ["valid-filter-outputs", "no-geo-trim--areaVars", "short"],
    ["valid-filter-outputs", "no-geo-trim--full-selVars", "short"],
    ["valid-filter-outputs", "no-geo-trim--no-row-bal", "short"],
    ["valid-filter-outputs", "no-geo-trim--no-vars-by-plant", "short"],
    ["valid-filter-outputs", "no-geo-trim--noVar", "short"],
    ["valid-filter-outputs", "no-geo-trim--selVars-1", "short"],
    ["valid-filter-outputs", "no-geo-trim--selVars-2", "short"],
    ["valid-filter-outputs", "no-geo-trim--selVars-3", "short"],
    ["valid-filter-outputs", "no-geo-trim--selVars-4", "short"],
    ["valid-filter-outputs", "no-geo-trim-adq-selVars-2", "short"],
    ["valid-filter-outputs", "with-geo-trim--no-vars-by-plant", "short"],
    ["valid-filter-outputs", "with-geo-trim--selVars-1", "short"],
    ["valid-filter-outputs", "with-geo-trim--selVars-2", "short"],
    ["valid-hydro", "H700-34", "short"],
    ["valid-hydro", "H701-52", "short"],
    ["valid-hydro", "H701-57", "short"],
    ["valid-hydro", "H701-58", "short"],
    ["valid-hydroPricing", "Fast/YHT-one_node_different styles/hydro-pricing-E_hb", "short"],
    ["valid-parallel", "Four areas - DC law_eco-acc-168", "short"],
    ["valid-thermal", "generic - all ON - some MUST - TSGEN", "short"],
    ["valid-thermal", "generic - some  OFF - no OFFMUST - TSGEN", "short"],
    ["valid-thermal", "generic - some  OFF - some MUST - TSGEN", "short"],
    ["valid-hydro", "H700-30", "short"],
    ["valid-hydro", "H701-53", "short"],
    ["valid-hydro", "H701-54", "short"],
    ["valid-hydro", "H701-55", "short"],
    ["valid-hydro", "H701-56", "short"],
    ["valid-hydro", "H701-59", "short"],
    ["valid-hydro", "H700-31", "short"],
    ["valid-hydro", "H700-51", "short"],
    ["valid-parallel", "test-paral-cplx-pl-7on12-scBuild_eco-fast-24", "short"],
    ["valid-parallel", "test-parallelisation-complexe-pl-2on12Y_eco-fast-24", "short"],
    ["valid-complex", "hydrau_FRCH", "short"],
    ["valid-parallel", "Multistage study-3-PTDF_eco-fast-24", "short"],
    ["valid-hydroPricing", "Accurate/YHT-five-areas/hydro-pricing-01", "short"],
    ["valid-hydroPricing", "Accurate/YHT-five-areas/hydro-pricing-02", "short"],
    ["valid-hydroPricing", "Accurate/YHT-five-areas/hydro-pricing-03", "short"],
    ["valid-hydroPricing", "Accurate/YHT-five-areas/hydro-pricing-04", "short"],
    ["valid-hydroPricing", "Fast/YHT-five-areas/hydro-pricing-01", "short"],
    ["valid-hydroPricing", "Fast/YHT-five-areas/hydro-pricing-02", "short"],
    ["valid-hydroPricing", "Fast/YHT-five-areas/hydro-pricing-03", "short"],
    ["valid-hydroPricing", "Fast/YHT-five-areas/hydro-pricing-04", "short"],
    ["valid-parallel", "test-paral-cplx-pl-7on12-scBuild_eco-acc-168", "short"],
    ["valid-parallel", "test-parallelisation-complexe-pl-2on12Y_eco-acc-168", "short"],
    ["valid-hydroPricing", "Accurate/YHT-five-areas/hydro-pricing-05", "short"],
    ["valid-hydroPricing", "Fast/YHT-five-areas/hydro-pricing-05", "short"],
    # MEDIUM STUDIES
    ["valid-parallel", "Multistage study-3-PTDF_eco-acc-168", "medium"],
    ["valid-hydroBind", "hydrobind-spxday-freemod", "medium"],
    ["valid-hydroBind", "hydrobind-Adequacy", "medium"],
    ["valid-hydroBind", "hydrobind-spxday-minexc", "medium"],
    ["valid-bind", "BIND-03-gen", "medium"],
    ["valid-hydro", "H700-44", "medium"],
    ["valid-hydro", "H700-32", "medium"],
    ["valid-hydroBind", "hydrobind-spxweek-freemod", "medium"],
    ["valid-draft", "052 Benchmark CPU RAM HDD - 4_draft", "medium"],
    ["valid-hydroBind", "hydrobind-spxweek-minexc", "medium"],
    ["valid-hydroBind", "hydrobind-draft", "medium"],
    ["valid-parallel", "test-parallel-02_eco-fast-24", "medium"],
    ["valid-parallel", "test-parallel-01_eco-fast-24", "medium"],
    ["valid-parallel", "test-parallel-02-noMustRun_eco-acc-168", "medium"],
    ["valid-parallel", "test-parallel-02-noMustRun_eco-fast-24", "medium"],
    ["valid-parallel", "test-parallel-01_eco-acc-168", "medium"],
    ["valid-parallel", "test-parallel-02_eco-acc-168", "medium"],
    ["valid-adq", "052 Benchmark CPU RAM HDD - 4_adq", "medium"],
    ["valid-bind", "BIND-00-gen", "medium"],
    ["valid-bind", "BIND-01-gen", "medium"],
    # LONG STUDIES
    ["valid-parallel", "test-parallel-03-random_nbrs_eco-fast-24", "long"],
    ["valid-bind", "BIND-02-gen", "long"],
    ["valid-complex", "E2050-5y-6w-fast-mps", "long"],
    ["valid-parallel", "test-parallel-03-random_nbrs_eco-acc-168", "long"],
    ["valid-complex", "E2050-5y-6w-accurate-mps", "long"]]

f=open("out.py", "w")

def fmt(x):
    return x.replace("-","_")\
            .replace("/", "_")\
            .replace(" ","")\
            .replace("__", "_")\
            .lower()

skip=False

for it in STUDIES:
    f.write(f"@pytest.mark.non_regression\n")
    f.write(f"@pytest.mark.{fmt(it[0])}\n")
    f.write(f"@pytest.mark.{it[2]}\n")
    if skip:
        f.write("@pytest.mark.skipif(sys.platform==\"linux\",\n")
        f.write("                    reason=\"Results different between linux and windows.\")\n")
    f.write(f"def test_{fmt(it[1])}(use_ortools, ortools_solver, solver_path):\n")
    f.write(f"    study_path = NONREG_STUDIES_PATH / \"{it[0]}\" / \"{it[1]}\"\n")
    f.write("    enable_study_output(study_path, True)\n")
    f.write("    run_study(solver_path, study_path, use_ortools, ortools_solver)\n")
    f.write("    check_output_values(study_path)\n\n")
