name: "Generate User Guide pdf"
description: "Generate User Guide pdf using Sphinx (not supported on windows)"
outputs:
  pdf-path:
    description: "path of the user guide pdf"
    value: ${{ steps.create.outputs.pdf-path }}
  pdf-name:
    description: "name of the user guide pdf"
    value: ${{ steps.create.outputs.pdf-name }}
runs:
  using: "composite"
  steps:
    - id: create
      shell: bash
      run: |
        PDF_NAME=antares-general-reference-guide.pdf
        cd docs/pdf-doc-generation-with-sphinx
        bash create_pdf_doc.sh $PDF_NAME
        mv antaressimulatoruserguide.pdf $PDF_NAME
        PDF_PATH=docs/$PDF_NAME
        echo "::set-output name=pdf-path::$PDF_PATH"
        echo "::set-output name=pdf-name::$PDF_NAME"
