#!/bin/bash

ANTARES_SRC=`pwd`

cd ..

git submodule update --init --recursive

cd src/ext

#CURL
cd ../libcurl
./buildconf
export LIBS="-ldl -lpthread"
./configure --disable-shared --disable-ldap --without-libidn --without-libssh2 --without-zlib
make

#export CC=/usr/local/gcc/4.8/bin/gcc-4.8
#export CXX=/usr/local/gcc/4.8/bin/g++-4.8

#wxWidgets
cd ../wxwidgets
mkdir build_gtk
cd build_gtk
../configure --with-gtk --disable-shared
make

cd $ANTARES_SRC
cmake -DCMAKE_BUILD_TYPE=release -DCMAKE_AR=/usr/bin/gcc-ar -DCMAKE_RANLIB=/usr/bin/gcc-ranlib .
make
