name: "Download extract .zip precompiled libraries"
description: "Download and extract .zip precompiled libraries from antares-deps and antares-simulator repository"
inputs:
  antares-deps-version:
    description: 'antares-deps version'
    required: true 
  os:
    description: 'operational system used for github action'
    required: true
  buildtype:
    description: 'build type'
    required: false
    default: 'Release'

runs:
  using: "composite"
  steps: 
  - id: download-extract
    shell: bash
    run: |
           wget https://github.com/AntaresSimulatorTeam/antares-deps/releases/download/v${{inputs.antares-deps-version}}/rte-antares-deps-${{inputs.os}}-${{inputs.buildtype}}-solver.zip
           unzip rte-antares-deps-${{inputs.os}}-${{inputs.buildtype}}-solver.zip
           rm -rf rte-antares-deps-${{inputs.os}}-${{inputs.buildtype}}-solver.zip