
!define ANTARES_ARCH         "@ANTARES_INSTALLER_ARCH@"
!define ANTARES_REDIST_ARCH  "@ANTARES_INSTALLER_REDIST_ARCH@"
!define TARGET               "@NSIS_TARGET@"

!define COMPILER_MARK        "@COMPILER_MARK@"
