
REM
REM --- File generated by make-zip-from-installer.cmake
REM

set ANTARES_ARCH=@ANTARES_INSTALLER_ARCH@
set VERSION=@ANTARES_VERSION_HI@.@ANTARES_VERSION_LO@.@ANTARES_VERSION_REVISION@@ANTARES_INSTALLER_BETA@@ANTARES_INSTALLER_RC@
set INSTALLER=rte-antares-%VERSION%-installer-%ANTARES_ARCH%
set CURRENT_DIR=%CD%


if not exist "%CURRENT_DIR%\%INSTALLER%.exe" goto error_prgm_missing 

if exist "%INSTALLER%" del /Q /S /F  "%INSTALLER%"

mkdir "%INSTALLER%"
copy "%INSTALLER%.exe" "%INSTALLER%" 
copy "..\\..\\..\\changelog.txt" "%INSTALLER%" 

..\..\..\bin\zip.exe -9 -r "%INSTALLER%.zip" "%INSTALLER%"

del /Q /S /F  "%INSTALLER%"

pause
goto end


:error_prgm_missing
REM The program %INSTALLER%.exe is missing. Please compile antares first

:end
