

!define CMAKE_VERSION '@ANTARES_VERSION_HI@.@ANTARES_VERSION_LO@.@ANTARES_VERSION_REVISION@'
!define CMAKE_VERSION_BUILD '@ANTARES_VERSION_REVISION@'
!define CMAKE_SIMPLE_VERSION '@ANTARES_VERSION_HI@.@ANTARES_VERSION_LO@'

!define CMAKE_PUBLISHER '@ANTARES_PUBLISHER@'
!define CMAKE_WEBSITE '@ANTARES_WEBSITE@'

!define CMAKE_BUILD_TARGET '@ANTARES_VERSION_TARGET@'
!define CMAKE_INSTALLER_EXTENSION '@ANTARES_INSTALLER_EXTENSION@'


!define CMAKE_INSTALLER_BETA  '@ANTARES_INSTALLER_BETA@'
!define CMAKE_INSTALLER_RC '@ANTARES_INSTALLER_RC@'

