name: C/C++ CI with dependency compilation

on:
  push:
    branches:
      - feature/cmake_build_dependency_option

jobs:     
         
  linux:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2 

    - name: Install libraries
      run: |
           sudo apt-get install libuuid1 uuid-dev libssh2-1 libssh2-1-dev libidn2-0 libidn2-dev libidn11 libidn11-dev gtk2.0 libb64-dev       

    - name: Configure
      run: |
           cd src
           mkdir _build
           cd _build
           cmake -DBUILD_DEPS=ON ..

    - name: Build
      run: |
           cd src
           cd _build
           cmake --build .
  windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2      

    - name: Configure
      run: |
           cd src
           mkdir _build
           cd _build
           cmake -DBUILD_DEPS=ON ..

    - name: Build
      run: |
           cd src
           cd _build
           cmake --build .          
           

