name: Centos7 CI (docker image)

on:
  push:
    branches:
      - develop
      - feature/*
      - features/*
      - fix/*
      - release/*
jobs:

  docker_publish:
          
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
        
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: |
          docker/centos7
        
    - name: Read antares-deps version
      if: steps.changed-files-specific.outputs.only_changed == 'true'
      id: antares-deps-version
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: 'antares-version.json'
        prop_path: 'antares_deps_version'
        
    - name: Docker file push
      if: steps.changed-files-specific.outputs.only_changed == 'true'
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        ANTARES_DEPS_VERSION: ${{steps.antares-deps-version.outputs.prop}}
      with:
        name: antaresrte/rte-antares
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: docker
        dockerfile: centos7
        cache: true
        tags: centos7-simulator
        buildargs: ANTARES_DEPS_VERSION

  build:

    runs-on: ubuntu-latest
    needs: docker_publish
    container: 'antaresrte/rte-antares:centos7-simulator'

    steps:
    
    - uses: nelonoel/branch-name@v1.0.1
    
    - name: Checkout
      run: |
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git -b ${BRANCH_NAME} .
    
    - name: Init submodule
      run: |
           git submodule update --init --recursive src .

    - name: Configure
      run: |
           source /opt/rh/devtoolset-7/enable
           cmake3 -B _build -S src -DDEPS_INSTALL_DIR=/rte-antares-deps-Release -DCMAKE_BUILD_TYPE=release -DBUILD_TESTING=ON -DBUILD_OUTPUT_TEST=ON

    - name: Build
      run: |
           source /opt/rh/devtoolset-7/enable
           cmake3 --build _build --config Release -j2
    
    - name: Run unit tests
      run: |
           cd _build
           ctest3 -C Release --output-on-failure -L "unit|end-to-end|short|medium" -LE ortools
           
    - name: Installer .rpm creation
      run: |
           cd _build
           cpack3 -G RPM
           
    - name: Installer .tar.gz creation
      run: |
           cd _build
           cpack3 -G TGZ
           
    - name: Installer archive upload
      uses: actions/upload-artifact@v2
      with:
        name: antares-centos7-archive
        path: _build/*.tar.gz
        
    - name: Installer rpm upload
      uses: actions/upload-artifact@v2
      with:
        name: antares-centos7-rpm
        path: _build/*.rpm

