name: Check cpp formatting using clang 18.1.3

on:
  pull_request:

jobs:
  build:
    name: clang-format

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print clang-format version
        run: clang-format --version

      - name: Run clang-format
        run: cd src && ./format-code.sh

      - name: Check for formatting changes
        id: check_diff
        run: |
          # Create a diff patch file
          git diff > diff.patch

          # Check for changes
          # DIFF=$(git status --porcelain)
          # echo "DIFF<<EOF" >> $GITHUB_ENV
          # echo $(git status --porcelain) >> $GITHUB_ENV
          # echo "EOF" >> $GITHUB_ENV

          # Optionally output the diff for debugging
          cat diff.patch

      - name: Suggest formatting changes in PR
        #if: env.DIFF != ''
        run: |
          # Install GitHub CLI
          sudo apt-get install -y gh
          gh auth login --with-token <<< "$GITHUB_TOKEN"

          # Create a comment with suggestions
          COMMENT_BODY="## Formatting Suggestions\n\n"
          while IFS= read -r line; do
            if [[ $line =~ ^@@ ]]; then
              line_number=$(echo $line | grep -oP '(?<=\+)[0-9]+')
            elif [[ $line =~ ^\+ ]]; then
              suggestion=$(echo "$line" | sed 's/^+//')
              COMMENT_BODY+="```suggestion\n$suggestion\n```\n"
            fi
          done < diff.patch

          # Add a comment to the PR
          gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT_BODY"
