name: C/C++ CI

on:
  push:
    branches:
      - NO_EXTLIB_BUILD

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04]

    steps:
    - uses: actions/checkout@v2

    - name: Install libraries
      run: |
           sudo apt-get update --fix-missing
           sudo apt-get install libuuid1 uuid-dev libssh2-1 libssh2-1-dev libidn2-dev libidn11 libidn11-dev gtk2.0 libwxgtk3.0-dev libcurl4-openssl-dev libb64-dev

    - name: Configure
      run: |
           cd src
           cmake .

    - name: Build
      run: |
           cd src
           make

