name: CI docker hub publish

on: 
  push:
    branches:
      - develop
      - feature/update_docker_hub_repo

jobs:

  docker_hub_publish:
    strategy:
      matrix:
        container:
        - 'centos8'
        - 'ubuntu'
        
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: OR-Tools and sirius build
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: antaresrte/rte-antares
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: docker
        dockerfile: ${{ matrix.container }}-ortools
        cache: true
        tags: ${{ matrix.container }}-ortools
        
    - name: Antares Simulator build
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: antaresrte/rte-antares
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: docker
        dockerfile: ${{ matrix.container }}-antares-build
        cache: true
        tags: ${{ matrix.container }}-antares-build
