name: Linux CI (system libs)

on:
  push:
    branches:
      - develop
      - feature/cmake_build_dependency_option
      - feature/ANT-457--cmake-with-ctest
      
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install libraries
      run: |
           sudo apt-get update --fix-missing
           sudo apt-get install libuuid1 uuid-dev libssh2-1 libssh2-1-dev libidn2-dev libidn11 libidn11-dev gtk2.0 libwxgtk3.0-dev libcurl4-openssl-dev libb64-dev

    - name: Configure
      run: |
           cmake -B _build -S src -DCMAKE_BUILD_TYPE=release

    - name: Build
      run: |
           cmake --build _build --config release -j2

    - name: Run unit tests
      run: |
           cd src
           cd _build
           ctest -C Release --output-on-failure
           
    - name: Installer .deb creation
      run: |
           cd _build
           cpack -G DEB
           
    - name: Installer .tar.gz creation
      run: |
           cd _build
           cpack -G TGZ
           
    - name: Installer upload
      uses: actions/upload-artifact@v2
      with:
        name: antares-installer-64bits
        path: _build/antares-*.*.*-Linux.*

