name: Linux CI (deps. compilation)

on:
  push:
    branches:
      - feature/cmake_build_dependency_option
      - feature/ANT-457--cmake-with-ctest

jobs:     
         
  linux:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        buildtype: [release]

    steps:
    - uses: actions/checkout@v2 

    - name: Install libraries
      run: |
           sudo apt-get install libuuid1 uuid-dev libssh2-1 libssh2-1-dev libidn2-0 libidn2-dev libidn11 libidn11-dev gtk2.0 libb64-dev

    - name: Configure with cmake
      run: |
           cd src
           mkdir _build
           cd _build
           cmake -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} -DBUILD_DEPS=ON -DBUILD_TESTING=ON ..

    - name: Build with cmake
      run: |
           cd src
           cd _build
           cmake --build . --config ${{ matrix.buildtype }} --parallel 4

    - name: Runnning unit tests
      run: |
           cd src
           cd _build
           ctest -C ${{ matrix.buildtype }}

