name: Linux CI (deps. compilation)

on:
  push:
    branches:
      - feature/cmake_build_dependency_option
      - develop

jobs:     
         
  linux:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2 

    - name: Install libraries
      run: |
           sudo apt-get install libuuid1 uuid-dev libssh2-1 libssh2-1-dev libidn2-0 libidn2-dev libidn11 libidn11-dev gtk2.0 libb64-dev       

    - name: Configure
      run: |
           cd src
           mkdir _build
           cd _build
           cmake -DBUILD_DEPS=ON ..

    - name: Build
      run: |
           cd src
           cd _build
           cmake --build .
    - name: Installer .deb creation
      run: |
           cd src
           cd _build
           cpack -G DEB .
    - name: Installer .tar.gz creation
      run: |
           cd src
           cd _build
           cpack -G TGZ .
    - name: Installer upload
      uses: actions/upload-artifact@v2
      with:
        name: antares-installer-64bits
        path: src/_build/antares-*.*.*-Linux.*
           

