name: Linux CI (deps. compilation)

on:
  push:
    branches:
      - develop
jobs:     
         
  linux:

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [ubuntu-latest]
        use_ortools_stable : ["OFF"]

    steps:
    - uses: actions/checkout@v2 

    - name: Install libraries
      run: |
           sudo apt-get update --fix-missing
           sudo apt-get install libuuid1 uuid-dev libssh2-1 libssh2-1-dev libidn2-0 libidn2-dev libidn11 libidn11-dev gtk2.0 libb64-dev       

    - name: Configure
      run: |
           cmake -B _build -S src -DBUILD_DEPS=ON -DCMAKE_BUILD_TYPE=release -DBUILD_TESTING=ON -DUSE_ORTOOLS_STABLE=${{ matrix.use_ortools_stable }}

    - name: Build
      run: |
           cmake --build _build --config release -j2


    - name: Runnning unit tests
      run: |
           cd _build
           ctest -C Release --output-on-failure

    - name: Installer .deb creation
      run: |
           cd _build
           cpack -G DEB

    - name: Installer .tar.gz creation
      run: |
           cd _build
           cpack -G TGZ

    - name: Installer upload
      uses: actions/upload-artifact@v2
      with:
        name: antares-installer-64bits
        path: _build/antares-*.*.*-Linux.*