name: Linux CI (deps. compilation)

on:
  push:
    branches:
      - feature/cmake_build_dependency_option
      - develop

jobs:     
         
  linux:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2 

    - name: Install libraries
      run: |
           sudo apt-get install libuuid1 uuid-dev libssh2-1 libssh2-1-dev libidn2-0 libidn2-dev libidn11 libidn11-dev gtk2.0 libb64-dev       

    - name: Configure
      run: |
           cmake -B _build -S src -DBUILD_DEPS=ON -DCMAKE_BUILD_TYPE=release

    - name: Build
      run: |
           cmake --build _build --config release

    - name: Installer .deb creation
      run: |
           cpack -G DEB _build

    - name: Installer .tar.gz creation
      run: |
           cpack -G TGZ _build

    - name: Installer upload
      uses: actions/upload-artifact@v2
      with:
        name: antares-installer-64bits
        path: _build/antares-*.*.*-Linux.*
           

