name: Create a nightly release everyday

on:
  push:
    branches:
      - feature/nightly_release
  schedule:
    - cron: '0 11 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.REF }}

      - name: Run nightly release
        uses: ./.github/workflows/publish-release
        with:
          target_branch: "develop"
          release_tag: "nightly"
          release_name: "nightly"
          run-tests: true
          set_latest: false