name: Create a nightly release everyday

on:
  push:
    branches:
      - feature/nightly_release
  schedule:
    - cron: '0 11 * * *'

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: 'nightly'
          title: 'nightly'
          tests: true
          target_branch: 'develop'
          latest: false
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="$title" \
              --notes="Run tests: $tests"\
              --target="$target_branch" \
              --latest=$latest
  
  
  ubuntu:
    name: Release - Ubuntu
    needs: release
    uses: ./.github/workflows/ubuntu.yml
    with:
      run-tests: false
      target_branch: 'develop'
  
  windows:
    name: Release - Windows
    needs: release
    uses: ./.github/workflows/windows-vcpkg.yml
    with:
      run-tests: false
      target_branch: 'develop'
  
  centos7:
    name: Release - centos7
    needs: release
    uses: ./.github/workflows/centos7.yml
    with:
      run-tests: false
      target_branch: 'develop'
  
  oracle8:
    name: Release - oracle8
    needs: release
    uses: ./.github/workflows/oracle8.yml
    with:
      run-tests: false
      target_branch: 'develop'
  
  user_guide:
    name: User Guide
    needs: release
    uses: ./.github/workflows/build-userguide.yml
    with:
      run-tests: false
      target_branch: 'develop'
