name: Oracle 8 CI (deps. compilation)

on:
  push:
    branches:
      - release/*
      - develop
      - feature/oracle

jobs:

  build:

    runs-on: ubuntu-latest
    container: 'oraclelinux:8'

    steps:

    - name: Set up Python
      run: |
           dnf update -y
           dnf install -y python3 python3-pip

    - name: Install libraries
      run: |
           dnf install -y git gcc-toolset-9-toolchain cmake wget rpm-build
           dnf install -y python3 python3-pip
           dnf install -y unzip libuuid-devel boost-test boost-devel

    - name: Checkout
      run: |
           git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git -b $GITHUB_REF_NAME .

    - name: Init submodule
      run: |
           git config --global safe.directory '*'
           git submodule update --init --recursive src .

    - name: Install dependencies
      run: |
          pip3 install -r src/tests/examples/requirements.txt

    - name: Configure
      run: |
           source /opt/rh/gcc-toolset-9/enable
           cmake -B _build -S src -DCMAKE_BUILD_TYPE=release -DBUILD_TESTING=ON -DBUILD_UI=OFF

    - name: Build
      run: |
           source /opt/rh/gcc-toolset-9/enable
           cmake --build _build --config release -j2

    - name: Installer .rpm creation
      run: |
           cd _build
           cpack -G RPM

    - name: Installer .tar.gz creation
      run: |
           cd _build
           cpack -G TGZ

    - name: Installer archive upload
      uses: actions/upload-artifact@v3
      with:
        name: antares-oracle8-archive
        path: _build/*.tar.gz

    - name: Installer rpm upload
      uses: actions/upload-artifact@v3
      with:
        name: antares-oracle8-rpm
        path: _build/*.rpm

