name: Release asset upload (Centos7)

on:
  release:
    types: [created]

env:
  GITHUB_TOKEN: ${{ github.token }}
  
jobs:

  windows:

    runs-on: ubuntu-latest
    container: 'centos:7'

    steps:
    
    - name: Set up Python
      run: |
           yum update -y
           yum install -y python3 python3-pip
          
    - name: Install mandatory system libraries
      run: |
           yum install -y wget git epel-release redhat-lsb-core gcc gcc-c++ make centos-release-scl scl-utils
           yum install -y openssl-devel curl-devel libuuid-devel wxGTK3-devel boost-test boost-filesystem boost-regex boost-devel 
           yum install -y cmake3 devtoolset-7 rpm-build
           
    - uses: nelonoel/branch-name@v1.0.1
    
    - name: Checkout
      run: |
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git -b ${BRANCH_NAME} .
    
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.0      
           
    - name: Download pre-compiled librairies
      run: |
           wget https://github.com/AntaresSimulatorTeam/antares-deps/releases/download/v1.1.0/rte-antares-deps-centos7-Release-solver.tar.gz
           tar -xvf rte-antares-deps-centos7-Release-solver.tar.gz
           rm -rf rte-antares-deps-centos7-Release-solver.tar.gz
           
    - name: Init submodule
      run: |
           git submodule update --init --recursive .
          
    - name: Install dependencies
      run: |
          pip3 install -r src/tests/examples/requirements.txt
    
    - name: Configure
      run: |
           source /opt/rh/devtoolset-7/enable
           cmake3 -B _build -S . -DDEPS_INSTALL_DIR=./rte-antares-deps-Release -DCMAKE_BUILD_TYPE=release -DBUILD_TESTING=ON
    
    - name: Build
      run: |
           source /opt/rh/devtoolset-7/enable
           cmake3 --build _build --config release -j2
    
    - name: Running unit tests
      run: |
           cd _build
           ctest3 -C release --output-on-failure -L "unit|end-to-end|short|medium" -LE ortools
               
    - name: Installer .rpm creation
      run: |
           cd _build
           cpack3 -G RPM
           export RPM_NAME=$(ls *.rpm)
           echo "RPM_NAME=$RPM_NAME" >> $GITHUB_ENV
           
    - name: .tar.gz creation
      run: |
           cd _build
           cpack3 -G TGZ
           export TGZ_NAME=$(ls *.tar.gz)
           echo "TGZ_NAME=$TGZ_NAME" >> $GITHUB_ENV
           
    - name: Upload .rpm
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: _build/${{env.RPM_NAME}}
        asset_name: ${{env.RPM_NAME}}
        asset_content_type: application/octet-stream
           
    - name: Upload .tar.gz
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: _build/${{env.TGZ_NAME}}
        asset_name: ${{env.TGZ_NAME}}
        asset_content_type: application/octet-stream
    
