name: Ubuntu CI (deps. compilation)

on:
  push:
    branches:
      - release/*
      - develop
jobs:

  linux:

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v3

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Install libraries
      run: |
           sudo apt-get update
           sudo apt-get install uuid-dev libwxgtk3.0-gtk3-dev
           sudo apt-get install libboost-test-dev

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip3 install -r src/tests/examples/requirements.txt

    - name: Init submodule
      run: |
           git submodule update --init --recursive src

    - name: Configure
      run: |
           cmake -B _build -S src -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER=/usr/bin/gcc-10 -DCMAKE_CXX_COMPILER=/usr/bin/g++-10 -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON

    - name: Build
      run: |
           cmake --build _build --config release -j2

    - name: Installer .deb creation
      run: |
           cd _build
           cpack -G DEB

    - name: Installer .tar.gz creation
      run: |
           cd _build
           cpack -G TGZ

    - name: Installer archive upload
      uses: actions/upload-artifact@v3
      with:
        name: antares-ubuntu-archive
        path: _build/*.tar.gz

    - name: Installer deb upload
      uses: actions/upload-artifact@v3
      with:
        name: antares-ubuntu-deb
        path: _build/*.deb
