name: Windows CI (deps. compilation)

on:
  push:
    branches:
      - feature/cmake_build_dependency_option

jobs:

  windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2      

    - name: Configure
      run: |
           cd src
           mkdir _build
           cd _build
           cmake -DBUILD_DEPS=ON -DCMAKE_BUILD_TYPE=release ..

    - name: Build
      run: |
           cd src
           cd _build
           cmake --build . --config release

    - name: Installer creation
      run: |
           cd src
           cd _build
           cpack -GNSIS
           
    - name: Installer creation
      uses: actions/upload-artifact@v2
      with:
        name: antares-installer-64bits
        path: src/_build/rte-antares-7.1.0-installer-64bits.exe          
           

