name: Windows CI (pre-compiled only)

on:
  push:
    branches:
      - release/*
      - develop
      - feature/review_github_workflow
jobs:

  windows:

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [windows-latest]
      
    steps:
    - uses: actions/checkout@v2
           
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        
    - name: Pre-requisites
      shell: cmd
      run: |          
          choco install wget unzip --no-progress
          
    - name: Download pre-compiled librairies
      uses: ./.github/workflows/download-extract-precompiled-libraries-zip
      with:
        antares-deps-version: ${{steps.antares-deps-version.outputs.prop}}
        os: ${{matrix.os}}
        artifact_version: all
        
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip3 install -r src/tests/examples/requirements.txt
           
    - name: Init submodule
      run: |
           git submodule update --init --recursive src

    - name: Configure
      run: |
           cmake -B _build -S src -DDEPS_INSTALL_DIR=rte-antares-deps-Release -DCMAKE_BUILD_TYPE=release -DBUILD_TESTING=ON -DBUILD_not_system=OFF -DUSE_PRECOMPILED_EXT=ON
           
    - name: Build
      run: |
           cmake --build _build --config release -j2

    - name: Test
      run: |
           cd _build
           ctest -C Release --output-on-failure -L "unit|end-to-end|short|medium" -LE ortools

    - name: NSIS Installer creation
      shell: bash
      run: |
           rm -rf src/tests/resources/Antares_Simulator_Tests
           rm -rf src/tests/resources/NonRegTests
           cd _build
           cpack -GNSIS
           export NSIS_NAME=$(ls *.exe)
           echo "NSIS_NAME=$NSIS_NAME" >> $GITHUB_ENV
           
    - name: .zip creation
      run: |
           cd _build
           cpack -G ZIP
           
    - name: Installer upload
      uses: actions/upload-artifact@v2
      with:
        name: antares-installer-64bits
        path: _build/${{env.NSIS_NAME}}
        
    - name: Archive upload
      uses: actions/upload-artifact@v2
      with:
        name: antares-windows-archive
        path: _build/*.zip
        
