name: Windows CI (deps. compilation)

on:
  push:
    branches:
      - feature/cmake_build_dependency_option
      - feature/ANT-457--cmake-with-ctest

jobs:

  windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        buildtype: [release]

    steps:
    - uses: actions/checkout@v2      

    - name: Configuring with cmake
      run: |
           cd src
           mkdir _build
           cd _build
           cmake -DCMAKE_BUILD_TYPE=release -DBUILD_DEPS=ON -DBUILD_TESTING=ON ..

    - name: Building with cmake
      run: |
           cd src
           cd _build
           cmake --build . --config release --parallel 4

    - name: Test
      run: |
           cd src
           cd _build
           ctest -C ${{ matrix.buildtype }}

    - name: Installer creation
      run: |
           cd src
           cd _build
           cpack -GNSIS
           
    - name: Installer creation
      uses: actions/upload-artifact@v2
      with:
        name: antares-installer-64bits
        path: src/_build/rte-antares-7.1.0-installer-64bits.exe          
           

