name: Windows CI (deps. compilation)

on:
  push:
    branches:
      - develop
jobs:

  windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        use_ortools_stable : ["OFF"]

    steps:
    - uses: actions/checkout@v2      

    - name: Configure
      run: |
           cmake -B _build -S src -DBUILD_DEPS=ON -DCMAKE_BUILD_TYPE=release -DBUILD_TESTING=ON -DUSE_ORTOOLS_STABLE=${{ matrix.use_ortools_stable }}
    
    - name: Remove dependency compilation directory
      uses: JesseTG/rm@v1.0.2
      with:
        path: _build/build_deps
           
    - name: Build
      run: |
           cmake --build _build --config release -j2

    - name: Test
      run: |
           cd _build
           ctest -C Release --output-on-failure

    - name: Installer creation
      run: |
           cd _build
           cpack -GNSIS
           
    - name: Installer upload
      uses: actions/upload-artifact@v2
      with:
        name: antares-installer-64bits
        path: _build/rte-antares-*.*.*-installer-*.exe