name: Windows CI (deps. compilation)

on:
  push:
    branches:
      - develop
      - feature/*
jobs:

  windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Download pre-compiled librairies
      run: |
           choco install wget
           wget https://github.com/AntaresSimulatorTeam/antares-deps/releases/download/v1.0.0/rte-antares-deps-${{matrix.os}}-x64-Release-ON.zip
           Expand-Archive ./rte-antares-deps-${{matrix.os}}-x64-Release-ON.zip -DestinationPath .
           rm rte-antares-deps-${{matrix.os}}-x64-Release-ON.zip
           
    - name: Init submodule
      run: |
           git submodule update --init --recursive src

    - name: Configure
      run: |
           ls
           cmake -B _build -S src -DDEPS_INSTALL_DIR=rte-antares-deps-Release -DCMAKE_BUILD_TYPE=release -DBUILD_TESTING=ON
           
    - name: Build
      run: |
           cmake --build _build --config release -j2

    - name: Test
      run: |
           cd _build
           ctest -C Release --output-on-failure

    - name: Installer creation
      run: |
           cd _build
           cpack -GNSIS
           
    - name: Installer upload
      uses: actions/upload-artifact@v2
      with:
        name: antares-installer-64bits
        path: _build/rte-antares-*.*.*-installer-*.exe